baseurl: "https://butter2019.netlify.app/"
languageCode: "en-us"
title: "ZhijunCV"
theme: "hugo-ivy"
googleAnalytics: "UA-151723808-1"
disqusShortname: "https-butter2019-netlify-com"
ignoreFiles: ["\\.Rmd$", "_cache$","\\.Rmarkdown$", "\\.knit\\.md$", "\\.utf8\\.md$"]
hasCJKLanguage: true
enableEmoji: true
footnotereturnlinkcontents: "↩"
rssLimit: 100

permalinks:
  cn: "/cn/:year/:month/:slug/"
  en: "/en/:year/:month/:slug/"

menu:
  main:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "About"
      url: "/en/about/"
      weight: 2
    - name: "Vitae"
      url: "/en/vitae/"
      weight: 3
    - name: "Publications"
      url: "/en/Publications/"
      weight: 4
    - name: "Blog"
      url: "/en/"
      weight: 5
    - name: "Contact"
      url: "/en/Contact"
      weight: 6
    - name: "中文"
      url: "/cn/"
      weight: 7
    
  en:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "About"
      url: "/en/about/"
      weight: 2
    - name: "Blog"
      url: "/en/"
      weight: 3
    - name: "Vitae"
      url: "/en/vitae/"
      weight: 4
    - name: "Publications"
      url: "/en/Publications/"
      weight: 5
    - name: "Contact"
      url: "/en/Contact"
      weight: 6
    - name: "中文"
      url: "/cn/"
      weight: 7
  cn:
    - name: "首页"
      url: "/"
      weight: 1
    - name: "简历"
      url: "/en/vitae/"
      weight: 2
    - name: "日志"
      url: "/cn/"
      weight: 3
    - name: "出版物"
      url: "/en/Publications/"
      weight: 4
    - name: "联系"
      url: "/cn/Contact/"
      weight: 5   
    - name: "English"
      url: "/en/"
      weight: 6
      
animation:
    - name: "Home"
      url: "/animation/"
      weight: 1
    - name: "Examples"
      url: "/animation/examples/"
      weight: 2
    - name: "Export"
      url: "/animation/export/"
      weight: 3
    - name: "Resources"
      url: "/animation/resources/"
      weight: 4
    - name: "Github repo"
      pre: "github"
      url: ""
      weight: 5
    - name: "name"
      url: "/"
      weight: 6
      
params:
  description: "Practice makes perfect :熟能生巧"
  footer: "&copy; [Zhijun Wang](/) 2021"
  disqusURL: "https://butter2019.netlify.com/"
  customJS:
    - "js/fix-toc.js"
    - "js/center-img.js"
    - "js/right-quote.js"
    - "js/no-highlight.js"
    - "js/fix-footnote.js"
    - "js/math-code.js"
    - "js/external-link.js"
    - "js/alt-title.js"
    - "js/header-link.js"

  # options for highlight.js (version, additional languages, and theme)
  highlightjsVersion: "9.12.0"
  highlightjsCDN: "//cdnjs.cloudflare.com/ajax/libs"
  highlightjsLang: ["r", "yaml", "tex"]
  highlightjsTheme: "github"

  logo:
    en:
      img: "/images/logo.png"
      url: "/"
      alt: "ZhijunCV"
      tag: ""
    
  author:
    en: "Zhijun"
    cn: ""
    animation: ""
  lang:
    edit:
      cn: "编辑"
    license:
      cn: "版权"
    subscribe:
      cn: "订阅"

blackfriday:
    extensionsmask: ["noIntraEmphasis"]
    fractions: false
