baseurl = 'https://butter2019.netlify.app/'
disqusShortname = ''
footnotereturnlinkcontents = '↩'
googleAnalytics = 'UA-151723808-1'
ignoreFiles = ['\.Rmd$', '\.Rmarkdown$', '_cache$', '\.knit\.md$', '\.utf8\.md$']
languageCode = 'en-us'
preserveTaxonomyNames = true
theme = 'hugo-ivy'
title = 'Zhijun Blog'
googlefonts = "//fonts.googleapis.com/css?family=Merriweather|Fira+Mono|Droid+Sans"
[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true



[menu]
[[menu.main]]
name = 'Home'
url = '/home/'
weight = 1
[[menu.main]]
name = 'About'
url = '/about/'
weight = 2
[[menu.main]]
name = 'Vitae'
url = '/vitae/'
weight = 3
[[menu.main]]
name = 'Publications'
url = '/publications/'
weight = 4
[[menu.main]]
name = 'Blog'
url = '/post/'
weight = 5
[[menu.main]]
name = 'Categories'
url = '/categories/'
weight = 6
[[menu.main]]
name = 'Contact'
url = '/contact/'
weight = 7
[[menu.main]]
name = 'Tags'
url = '/tags/'
weight = 8



[params]
description = 'Practice makes perfect :熟能生巧.'
footer = '&copy; [Zhijun Wang](https://zhijunwang.me) 2019-2021'
highlightjsCDN = '//cdn.bootcss.com'
highlightjsLang = ['r', 'yaml', 'tex']
highlightjsTheme = 'github'
highlightjsVersion = '9.12.0'

[permalinks]
note = '/note/:year/:month/:day/:slug/'
post = '/post/:year/:month/:day/:slug/'
