baseurl = 'https://butter2019.netlify.app/'
disqusShortname = ''
footnotereturnlinkcontents = '↩'
googleAnalytics = 'UA-151723808-1'
ignoreFiles = ['\.Rmd$', '\.Rmarkdown$', '_cache$', '\.knit\.md$', '\.utf8\.md$']
languageCode = 'en-us'
preserveTaxonomyNames = true
theme = 'hugo-ivy'
title = 'Food & Data'
googlefonts = "//fonts.googleapis.com/css?family=Merriweather|Fira+Mono|Droid+Sans"
[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true



[menu]

[[menu.main]]
name = 'Home'
url = '/'
weight = 1

[[menu.main]]
name = 'Vitae'
url = '/vitae/'
weight = 2

[[menu.main]]
name = 'Publications'
url = '/publications/'
weight = 3

[[menu.main]]
name = 'Blog'
url = '/post/'
weight = 4

[[menu.main]]
name = 'Categories'
url = '/categories/'
weight = 5

[[menu.main]]
name = 'Tags'
url = '/tags/'
weight = 6

[params]
description = 'Practice makes perfect.'
footer = '&copy; [Zhijun Wang](https://zhijunwang.me) 2019 - now'
highlightjsCDN = '//cdn.bootcss.com'
highlightjsLang = ['r', 'yaml', 'tex']
highlightjsTheme = 'github'
highlightjsVersion = '9.12.0'

[permalinks]
note = '/note/:year/:month/:day/:slug/'
post = '/post/:year/:month/:day/:slug/'
