baseurl: "https://butter2019.netlify.com/"
languageCode: "en-us"
title: "Butter"
theme: "hugo-ivy"
googleAnalytics: "UA-151723808-1"
disqusShortname: "https-butter2019-netlify-com"
ignoreFiles: ["\\.Rmd$", "_files$", "_cache$"]
hasCJKLanguage: true
enableEmoji: true
footnotereturnlinkcontents: "↩"
rssLimit: 100

permalinks:
  cn: "/cn/:year/:month/:slug/"
  en: "/en/:year/:month/:slug/"

menu:
  main:
    - name: "About"
      url: "/en/about/"
      weight: 1
    - name: "Blog"
      url: "/en/"
      weight: 2
    - name: "关于"
      url: "/cn/about/"
      weight: 3
    - name: "日志"
      url: "/cn/"
      weight: 4
  en:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "About"
      url: "/en/about/"
      weight: 2
    - name: "Blog"
      url: "/en/"
      weight: 3
    - name: "Vitae"
      url: "/en/vitae/"
      weight: 4
    - name: "中文"
      url: "/cn/"
      weight: 5
  cn:
    - name: "首页"
      url: "/"
      weight: 1
    - name: "关于"
      url: "/cn/about/"
      weight: 2
    - name: "日志"
      url: "/cn/"
      weight: 3
    - name: "简历"
      url: "/cn/vitae/"
      weight: 4
    - name: "书单"
      url: "/cn/book/"
      weight: 5
    - name: "English"
      url: "/en/"
      weight: 6
animation:
    - name: "Home"
      url: "/animation/"
      weight: 1
    - name: "Examples"
      url: "/animation/examples/"
      weight: 2
    - name: "Export"
      url: "/animation/export/"
      weight: 3
    - name: "Resources"
      url: "/animation/resources/"
      weight: 4
    - name: "Github repo"
      pre: "github"
      url: ""
      weight: 5
    - name: "name"
      url: "/"
      weight: 6
      
params:
  description: "Practice makes perfect ; 熟能生巧"
  footer: "&copy; [Butterdata|黄油数据](/) 2018 - 2019"
  disqusURL: "https://butter2019.netlify.com/"
  customJS:
    - "js/fix-toc.js"
    - "js/center-img.js"
    - "js/right-quote.js"
    - "js/no-highlight.js"
    - "js/fix-footnote.js"
    - "js/math-code.js"
    - "js/external-link.js"
    - "js/alt-title.js"
    - "js/header-link.js"

  # options for highlight.js (version, additional languages, and theme)
  highlightjsVersion: "9.12.0"
  highlightjsCDN: "//cdnjs.cloudflare.com/ajax/libs"
  highlightjsLang: ["r", "yaml", "tex"]
  highlightjsTheme: "github"

  logo:
    en:
      img: "/images/logo.png"
      url: "/"
      alt: "Butter"
      tag: ""
    
  author:
    en: "Butter"
    cn: "黄油"
    animation: "Butter & milk"
  lang:
    edit:
      cn: "编辑"
    license:
      cn: "版权"
    subscribe:
      cn: "订阅"

blackfriday:
    extensionsmask: ["noIntraEmphasis"]
    fractions: false
