baseurl = 'https://zhijunwang.me/'

footnotereturnlinkcontents = '↩'
googleAnalytics = 'G-XEQWJYE7S4'
ignoreFiles = ['\.Rmd$', '\.Rmarkdown$', '_cache$', '\.knit\.md$', '\.utf8\.md$']
languageCode = 'en-us'
hasCJKLanguage = true
preserveTaxonomyNames = true
theme = 'hugo-ivy'
title = 'Food & Data'

googlefonts = "//fonts.googleapis.com/css?family=Merriweather|Fira+Mono|Droid+Sans"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true



[menu]

[[menu.main]]
name = 'Home'
url = '/'
weight = 1

[[menu.main]]
name = 'Vitae'
url = '/vitae/'
weight = 2

[[menu.main]]
name = 'Publications'
url = '/publications/'
weight = 3

[[menu.main]]
name = 'Blog'
url = '/post/'
weight = 4

[[menu.main]]
name = 'Categories'
url = '/categories/'
weight = 5

[[menu.main]]
name = 'Tags'
url = '/tags/'
weight = 6

[[menu.main]]
name = 'Gallery'
url = '/gallery/'
weight = 7

[params]
description = 'Practice makes perfect.'
footer = '&copy; [Zhijun Wang](https://zhijunwang.me) 2019-2022'
highlightjsCDN = '//cdn.bootcss.com'
highlightjsLang = ['r', 'yaml', 'tex']
highlightjsTheme = 'github'
highlightjsVersion = '9.12.0'

[params.giscus]
  # repo = "github-user/github-repo" # Entering repo will enable giscus
  repo = "ZhijunWang1991/zhijunwang.me"
  repo_id = "MDEwOlJlcG9zaXRvcnkxODk1ODA0NDk="
  category = "Announcements"
  category_id = "DIC_kwDOC0zEoc4CS1ka"
  mapping = "pathname"
  reactions-enabled = "1"
  emit-metadata = "0"
  theme = "preferred_color_scheme"
  lang = "en"

[permalinks]
note = '/note/:year/:month/:day/:slug/'
post = '/post/:year/:month/:day/:slug/'
